### ISSUE TITLE
Sensitive user information still in repo

### ISSUE THREAD

**Issue by tinybarks** [whaliam/GoodUserBot_#1]
Your sensitive user information is still in the repository. When you send in a commit, instead of just storing new versions of the file, git will store the differences from the version of the repo the commit is based on to save space and make it possible to look at how something looked like at any point in the repo's history. [The sensitive information can thus still accessed.](https://github.com/whaliam/GoodUserBot_/commit/6994a7e56c625c8f5c6929e235809adb0fd21f00)

Follow this guide: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Or just recreate the repo.  **Either way, make sure to change the compromised information!**

**Comment by whaliam** [comment]
Fixed! Kept the commits but changed the password on reddit. Thanks!
